apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mediator
  name: mediator
spec:
  type: LoadBalancer
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      nodePort: 30163
      protocol: TCP
    - name: "9090"
      port: 9090
      targetPort: 9090
  selector:
    io.kompose.service: mediator
status:
  loadBalancer: { }